### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by spitfiredd** [18F/pyfpds#6]
I am getting an error what I try to run your example, here is my traceback.

`querying https://www.fpds.gov/ezsearch/FEEDS/ATOM?FEEDNAME=PUBLIC&q=PIID:FA865014M5002&start=0
Traceback (most recent call last):
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 291, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Anaconda3\envs\data_science\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Anaconda3\envs\data_science\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Anaconda3\envs\data_science\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Anaconda3\envs\data_science\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Anaconda3\envs\data_science\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\packages\urllib3\connection.py", line 190, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 124, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Anaconda3\envs\data_science\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Anaconda3\envs\data_science\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Anaconda3\envs\data_science\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Anaconda3\envs\data_science\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\adapters.py", line 327, in send
    timeout=timeout
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 520, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\spitf\G2XChange\python_libs\pyfpds-master\pyfpds\__init__.py", line 130, in get
    resp = requests.get(self.feed_url + params + '&start={0}'.format(i), timeout=60)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda3\envs\data_science\lib\site-packages\requests\adapters.py", line 382, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)`

**Comment by spitfiredd** [comment]
I fixed this by changing:
`resp = requests.get(self.feed_url + params + '&start={0}'.format(i), timeout=60)`

to:
`resp = requests.get(self.feed_url + params + '&start={0}'.format(i), timeout=60, verify=False)`

**Comment by tbaxter-18f** [comment]
Resolved with #8
